# Multi-Class Logistic Regression Using Scikit-Learn

In [73]:
# Load libraries
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.cross_validation import train_test_split
from sklearn import metrics
from sklearn.preprocessing import label_binarize
import warnings

# Suppress Warning
warnings.filterwarnings(action="ignore", module="scipy", message="^internal gelsd")

# Load Iris Flower Dataset

In [78]:
iris = datasets.load_iris()
X = iris.data
y = iris.target

# Standardize Features

In [79]:
# Standarize features
scaler = StandardScaler()
X_std = scaler.fit_transform(X)

# Create logistic regression

In [80]:
# Create logistic regression object
clf = LogisticRegression(random_state=0)

In [81]:
# Train model
model1 = clf.fit(X_std, y)

In [82]:
model1.intercept_

array([-1.61861686, -0.89769778, -2.70851029])

In [83]:
model1.coef_

array([[-0.81016631,  1.39369878, -1.68738578, -1.51899135],
       [ 0.13037985, -1.2463382 ,  0.78919477, -0.88943988],
       [ 0.01299039, -0.1445346 ,  1.86317337,  2.69887272]])

In [84]:
model1.score(X_std, y)

0.92666666666666664

# Train Logistic Regression Using SAG solver

In [85]:
# Create logistic regression object using sag solver
clf = LogisticRegression(solver='sag',random_state=0)

# Train model
model2 = clf.fit(X_std, y)

In [86]:
model2.intercept_

array([-2.48478977, -0.93821439, -3.79951294])

In [87]:
model2.coef_

array([[-1.05903725,  1.22294709, -1.76426377, -1.63734782],
       [ 0.13003099, -1.26242676,  0.79587666, -0.8919623 ],
       [ 0.13996749, -0.51271371,  2.48225359,  3.14081927]])

In [88]:
model2.score(X_std, y)

0.94666666666666666

# Make Classes Imbalanced

In [89]:
# Make class highly imbalanced by removing first 40 observations
X = X[40:,:]
y = y[40:]

# Create target vector indicating if class 0, otherwise 1
y = np.where((y == 0), 0, 1)

# Standardize Features

In [90]:
# Standarize features
scaler = StandardScaler()
X_std = scaler.fit_transform(X)

# Create Logistic Regression

In [91]:
# Create logistic regression object
clf = LogisticRegression(random_state=0,class_weight='balanced')

# Train Logistic Regression

In [94]:
# Train model
model3 = clf.fit(X_std, y)

In [95]:
model3.coef_

array([[ 0.39556683, -0.89716831,  1.39158012,  0.89447535]])

In [96]:
model3.intercept_

array([ 2.66786238])

In [97]:
model3.score(X_std, y)

1.0